# docker image build -t material.angular.io:v0.1 .
# docker run -d -p 6060:80 material.angular.io:v0.1
# docker run -ti material.angular.io:v0.1 bash

FROM nginx:latest

RUN apt-get update
RUN apt-get install -y \
    git \
    curl \
    gnupg \
    apt-transport-https

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get -y install python build-essential nodejs

RUN npm i -g npm@5.6.0 \
    && npm install -g @angular/cli

WORKDIR /src

RUN cd /src \
    && git clone https://github.com/angular/material.angular.io.git \
    && cd material.angular.io \
    && npm install
#     && ng build

# RUN rm -rf /usr/share/nginx/html \
#     && ln -s /src/material.angular.io/dist/ /usr/share/nginx/html


#https://github.com/angular/material2.git
#npm install --global gulp